### ISSUE TITLE
Scans once then scanner has to be restarted

### ISSUE THREAD

**Issue by vegas23** [klep/scanline#19]
macOS 10.12.4
Scanner: Epson DS-510

After using scanline to scan a document (which does work!) the scanner has to be power cycled before it works again. Is there some sort of call to reset the scanner that is not happening?

**Comment by klep** [comment]
I had similar issues with my Epson WorkForce 635. Long story short -- try updating the drivers from Epson's web site. You might also have a stray scanner process running (`ps aux | grep -i scan`) that you could kill. But for me, updating the driver did the trick.
