### ISSUE TITLE
Build fails in Xcode

### ISSUE THREAD

**Issue by RomanticStrings** [klep/scanline#2]
Thank you for this wonderful app.  I had the binary, but wanted to add the -mono capability.  I am having trouble building in Xcode.  These are the errors:

![screen shot 2015-09-07 at 8 13 02 pm](https://cloud.githubusercontent.com/assets/7991648/9724447/e5e194fc-559c-11e5-9c23-bb19f99611b7.png)

I can provide more info if you need it.

Best,
Conor Cook

**Comment by RomanticStrings** [comment]
I discovered that I can use the executable from the Products folder in Xcode as my command line exec file.  Thank you!

**Comment by klep** [comment]
I'd still like to fix the build error though. OCMock.framework should be included in the project directory and visible under "Frameworks" in XCode. I just downloaded and built it without any issues -- which version of XCode are you using?

**Comment by RomanticStrings** [comment]
Thank you.  Version 6.3.1 (6D1002).  It is under the "Frameworks" tab, but it only shows the Headers folder, whereas in my repository, it shows Headers, Resources, Versions, and an OCMock exec file.

**Comment by RomanticStrings** [comment]
I am sorry I never responded to this email.  I was sure I had.  I will
check when I get back to my personal computer, but I did update XCode, and
I think I tried to build after that, too.

~Conor

**Comment by RomanticStrings** [comment]
I have XCode 6.4.

I just tried to build it again, and it failed.

**Comment by klep** [comment]
Sorry for the delay. If you don't mind re-downloading and trying again, I may have fixed it. I also added a -help option that gives an overview of configuration options

**Comment by RomanticStrings** [comment]
Scott,

Thank you.  I did run it in XCode, and it built successfully, but with a
few messages.  I am not getting the -help options, though, when I run from
command-line.

~Conor

**Comment by RomanticStrings** [comment]
Here is the list of issues.  It seems that there is some disconnect between
the versions.

**Comment by klep** [comment]
I don't think the list came through, but they are likely warnings that don't affect the app if it built successfully.

Are you sure you're running the version that you built? Check the timestamp on the executable to make sure. The help command is:

scanline -help

The build output may be in a weird place, like ~/Library/Developer/Xcode/DerivedData/scanline-[something]/Build/Products/Debug/scanline

**Comment by klep** [comment]
(I'm also looking into ways to make this easier so you don't have to build it yourself)
