### ISSUE TITLE
batch scanning

### ISSUE THREAD

**Issue by kasclark** [klep/scanline#25]
First of all, this is a great tool! It's really helping me to clean out my filing cabinet. 

Anyway, I'm having some issues with the batch scanning option. The first scan goes fine, and then I'm prompted to press ENTER for the second page, or S to stop. Either way, nothing happens. No scan takes place, no file is created, nothing. It appears the program is still waiting for user input. 

`$ ./scanline -batch -flatbed school`
`Starting scan...`
`Press RETURN to scan next page or S to stop`
` `
`s`
`S`
` `

**Comment by klep** [comment]
Thanks for pointing this out, @kasclark -- just updated with a fix.
