### ISSUE TITLE
multiple printers can only scan from first in -list

### ISSUE THREAD

**Issue by shadowuilf** [klep/scanline#28]
im trying to implement scanline to save some time at work but when you use -list it shows around 20 printers available, but when you use -scanner you can only use the first in the list, if you try any others it says scanner could not be found. 
has anyone else on here used scanline with multiple scanners on mojave?

**Comment by klep** [comment]
@shadowuilf I'll check it out soon -- maybe there was a regression in one of the more recent releases. It sounds like you have a lot more scanners than me on your network though, so maybe that's a factor.

Can you reply with the exact parameters you're sending?

**Comment by klep** [comment]
@shadowuilf I only have 3 scanners on my network, but no issues selecting them. Is this similar to the parameters you're using?

```
