### ISSUE TITLE
Binary doesn't work in Catalina anymore

### ISSUE THREAD

**Issue by rennefJ** [klep/scanline#32]
I found this project and wanted to try scanline.
When I download the binary and try to run under macOS Catalina 10.15.5 I only get an error message saying:
"scanline" cannot be opened, apple cannot look for malwire inside.
This software needs to be updated.

Sadly I am not able to compile the source myself.
Could you provide an updated binary?
Or maybe add instructions on how to compile the tools?

best regards
Joerg

**Comment by klep** [comment]
@rennefJ -- If you go to System Preferences -> Security & Privacy after attempting to launch scanline, it should give you an open to open it anyway even though it's not signed.

**Comment by rennefJ** [comment]
@klep 
Thank you for this tip.
Sure enough, it works after allowing it in Security & Privacy
