### ISSUE TITLE
-flatbed does not work in installed version

### ISSUE THREAD

**Issue by jab11** [klep/scanline#35]
my scanner is Brother MFC-L2730DW series
I'm running `scanline -batch -flatbed docs` but I'm getting an error:
```
Searching for available scanners
Waiting up to 10.0 seconds to find scanners
Found scanner: Brother MFC-L2730DW series
Opening session with scanner
didOpenSessionWithError: [no error]
deviceDidBecomeReady
didSelectFunctionalUnit:  error: [no error]
Configuring scanner
Configuring Flatbed
Starting scan...
didEncounterError: An error occurred during scanning.
Failed to scan document.
Done
```

scanning from the document feeder works fine.

I downloaded the xcode project and ran the same command and that seems to work fine with -flatbed, is there a difference from the installed version ?

**Comment by jab11** [comment]
more info:
running the project from xcode works with `-flatbed`
exporting the project and running from commandline fails when using `-flatbed`, but works without it

**Comment by KaarlisCaune** [comment]
I'm using Epson V370 (no document feeder), and experiencing the same issue.
* Running in xcode with `-flatbed` works
* Running exported build with `-flatbed` errors with `didEncounterError: An error occurred during scanning. Failed to scan document.`

**Comment by klep** [comment]
@KaarlisCaune , when you say "exported build", do you mean a build that you made in XCode? Or the pre-built binary in git?

**Comment by klep** [comment]
Quick update -- I was able to repro this issue using the .dmg image linked in the README. Not sure yet if that binary is from a bad build or if it's something else. In the interim, please make a build from Xcode and grab the generated binary instead of using what's linked from the README

**Comment by klep** [comment]
Looks like this is a difference between what happens when checking non-optionals for `nil` in Debug vs. Release builds. The `didSelect functionalUnit` delegate method can give you a non-optional that's `nil` (which is a API bug) but in `Release`, checking it against `nil` will always return `false` (an optimization I suppose since it never should be `nil`). I've got a fix coming that instead checks its address against `0x0`.

**Comment by klep** [comment]
@jab11 @KaarlisCaune Please give this a try: https://github.com/klep/scanline/blob/master/scanline-1.0.1.pkg?raw=true
