### ISSUE TITLE
PKG not installable on MacOS Ventura

### ISSUE THREAD

**Issue by aixakt** [klep/scanline#41]
Hi, the PKG cannot be installed on MacOS Ventura Beta 3.

Best Regards
Ralph

<img width="296" alt="scanline_not_compatible_ventura" src="https://user-images.githubusercontent.com/5098382/177954747-a2018ec7-b23b-4ee9-88a1-0cb764fd5768.png">

**Comment by klep** [comment]
Was able to repro, though my attempts to work around it were unsuccessful. I think perhaps the best way forward is to get scanline added as a Homebrew formula. That would require an install script to be written, which I don't have time to do right now. If someone else would like to look into it, happy to review any PRs.

**Comment by oli-arborum** [comment]
I would be interested in with which versions of macOS scanline is compatible with.
I got the same error trying to install the 2.0 PKG under macOS 12.7 (Monterey).

**Comment by oli-arborum** [comment]
Same error when trying to install under macOS 13.6.1 (Ventura).

**Comment by klep** [comment]
@oli-arborum -- scanline is compatible with Ventura and Monterey. It's the installer that isn't. Will try to find some time to look into it over the holidays. Until then, building from source is the best bet.

**Comment by klep** [comment]
@oli-arborum and @aixakt -- I believe this has been fixed with the latest installer. Please give a shot if you can!

**Comment by oli-arborum** [comment]
Thanks, the pkg file was installable on macOS 13.6.1 (Ventura) and scanline works as expected.
(I cannot try it any more on Monterey, because I updated the machine to Ventura.)
