### ISSUE TITLE
2.0 installer only installs /receipts

### ISSUE THREAD

**Issue by Iraijus** [klep/scanline#43]
I tried using the 2.0 pkg installer, but I could not find the application anywhere. When choosing another location to install the app, it became obvious that the only thing that was being 'installed' was a /receipts directory with .bom and .plist files. I have not used macOS in a long time, but should 'scanline' not just work in the terminal?

Installing on High Sierra.

**Comment by klep** [comment]
@Iraijus -- I just updated the installer, which may resolve the issues you're seeing
