### ISSUE TITLE
Feature: Paper Size

### ISSUE THREAD

**Issue by bigtomjp** [klep/scanline#5]

**Comment by klep** [comment]
Paper size can be specified with -letter or -legal. Is there something else that you need?

**Comment by bigtomjp** [comment]
I  end up scanning a number of sizes of things. But as a start A4 and A6 would be nice. I am not sure how difficult it would be to access all the default paper sizes or use custom sizes. 

Right now I have small things sitting on a big US letter size page and it makes it difficult to deal with viewing and also causes extra data storage. 

Thanks

Tom

**Comment by rquast** [comment]
https://github.com/rquast/jsonscan - offers all document types supported by scanner.
